server:
  port: 8080

spring:
  cloud:
    azure:
      keyvault:
        secret:
          property-sources[0]:
            endpoint: https://cargocompare.vault.azure.net/

  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: ${mysql-url-dev}
    username: ${mysql-username-dev}
    password: ${mysql-password-dev}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail-username-dev}
    password: ${mail-appPassword-dev}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

application:
  security:
    jwt:
      secret-key: ${jwt-secret-dev}
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days



## FOR DEBUGGING
#server:
#  port: ${PORT:8080}
#
#
#spring:
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#
#  datasource:
#    url: jdbc:mysql://switchyard.proxy.rlwy.net:17158/railway
#    username: root
#    password: MNBLxSLzpdgwSxKUUVUFesqIEGFzTbAV
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: noreplycomparecargo@gmail.com
#    password: tqnl poey jcqr cdch
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#
#application:
#  security:
#    jwt:
#      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
#      expiration: 86400000 # a day
#      refresh-token:
#        expiration: 604800000 # 7 days
#
